// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AiDrawingGet implements GET /ai-drawing operation.
//
// Retrieve surrounding drawings only for dev mode.
//
// GET /ai-drawing
func (UnimplementedHandler) AiDrawingGet(ctx context.Context) (r AiDrawingGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HumanDrawingPost implements POST /human-drawing operation.
//
// Upload human drawing using the presigned URL obtained from /upload-url.
//
// POST /human-drawing
func (UnimplementedHandler) HumanDrawingPost(ctx context.Context, req *HumanDrawingPostReq) (r HumanDrawingPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SavedURLPost implements POST /saved-url operation.
//
// Save drawing URL in storage to BE.
//
// POST /saved-url
func (UnimplementedHandler) SavedURLPost(ctx context.Context, req *SavedURLPostReq) (r SavedURLPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadURLGet implements GET /upload-url operation.
//
// Retrieve presigned URLs for downloading surrounding drawings from cloud storage.
//
// GET /upload-url
func (UnimplementedHandler) UploadURLGet(ctx context.Context) (r UploadURLGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
