// Code generated by ogen, DO NOT EDIT.
package ogen

type GeneratePostRes interface {
	generatePostRes()
}

type InitGetRes interface {
	initGetRes()
}

type RebaseDatabaseGetRes interface {
	rebaseDatabaseGetRes()
}

type ViewGetRes interface {
	viewGetRes()
}
