// Code generated by ogen, DO NOT EDIT.
package ogen

type AiDrawingGetRes interface {
	aiDrawingGetRes()
}

type HumanDrawingPostRes interface {
	humanDrawingPostRes()
}

type SavedURLPostRes interface {
	savedURLPostRes()
}

type UploadURLGetRes interface {
	uploadURLGetRes()
}
