// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ImageGenerationPost implements POST /image-generation operation.
//
// Post the resource path in storage to BE.
//
// POST /image-generation
func (UnimplementedHandler) ImageGenerationPost(ctx context.Context, req *ImageGenerationPostReq) (r ImageGenerationPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PresignedUrlsGet implements GET /presigned-urls operation.
//
// Retrieve presigned URLs for both Human and AI drawings.
//
// GET /presigned-urls
func (UnimplementedHandler) PresignedUrlsGet(ctx context.Context) (r PresignedUrlsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
