// Code generated by ogen, DO NOT EDIT.
package ogen

type GeneratePostRes interface {
	generatePostRes()
}

type InitGetRes interface {
	initGetRes()
}

type RebootPostRes interface {
	rebootPostRes()
}

type ViewGetRes interface {
	viewGetRes()
}
