// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	ht "github.com/ogen-go/ogen/http"
)

// AiDrawingGetBadRequest is response for AiDrawingGet operation.
type AiDrawingGetBadRequest struct{}

func (*AiDrawingGetBadRequest) aiDrawingGetRes() {}

// AiDrawingGetInternalServerError is response for AiDrawingGet operation.
type AiDrawingGetInternalServerError struct{}

func (*AiDrawingGetInternalServerError) aiDrawingGetRes() {}

type AiDrawingGetOK struct {
	Result AiDrawingGetOKResult `json:"result"`
}

// GetResult returns the value of Result.
func (s *AiDrawingGetOK) GetResult() AiDrawingGetOKResult {
	return s.Result
}

// SetResult sets the value of Result.
func (s *AiDrawingGetOK) SetResult(val AiDrawingGetOKResult) {
	s.Result = val
}

func (*AiDrawingGetOK) aiDrawingGetRes() {}

type AiDrawingGetOKResult struct {
	TopDrawing    OptString `json:"topDrawing"`
	RightDrawing  OptString `json:"rightDrawing"`
	BottomDrawing OptString `json:"bottomDrawing"`
	LeftDrawing   OptString `json:"leftDrawing"`
}

// GetTopDrawing returns the value of TopDrawing.
func (s *AiDrawingGetOKResult) GetTopDrawing() OptString {
	return s.TopDrawing
}

// GetRightDrawing returns the value of RightDrawing.
func (s *AiDrawingGetOKResult) GetRightDrawing() OptString {
	return s.RightDrawing
}

// GetBottomDrawing returns the value of BottomDrawing.
func (s *AiDrawingGetOKResult) GetBottomDrawing() OptString {
	return s.BottomDrawing
}

// GetLeftDrawing returns the value of LeftDrawing.
func (s *AiDrawingGetOKResult) GetLeftDrawing() OptString {
	return s.LeftDrawing
}

// SetTopDrawing sets the value of TopDrawing.
func (s *AiDrawingGetOKResult) SetTopDrawing(val OptString) {
	s.TopDrawing = val
}

// SetRightDrawing sets the value of RightDrawing.
func (s *AiDrawingGetOKResult) SetRightDrawing(val OptString) {
	s.RightDrawing = val
}

// SetBottomDrawing sets the value of BottomDrawing.
func (s *AiDrawingGetOKResult) SetBottomDrawing(val OptString) {
	s.BottomDrawing = val
}

// SetLeftDrawing sets the value of LeftDrawing.
func (s *AiDrawingGetOKResult) SetLeftDrawing(val OptString) {
	s.LeftDrawing = val
}

type ApiKeyAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyAuth) SetAPIKey(val string) {
	s.APIKey = val
}

type HumanDrawingPostBadRequest struct {
	Error OptString `json:"error"`
}

// GetError returns the value of Error.
func (s *HumanDrawingPostBadRequest) GetError() OptString {
	return s.Error
}

// SetError sets the value of Error.
func (s *HumanDrawingPostBadRequest) SetError(val OptString) {
	s.Error = val
}

func (*HumanDrawingPostBadRequest) humanDrawingPostRes() {}

type HumanDrawingPostOK struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HumanDrawingPostOK) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HumanDrawingPostOK) SetMessage(val OptString) {
	s.Message = val
}

func (*HumanDrawingPostOK) humanDrawingPostRes() {}

type HumanDrawingPostReq struct {
	// The image file to upload.
	Image OptMultipartFile `json:"image"`
}

// GetImage returns the value of Image.
func (s *HumanDrawingPostReq) GetImage() OptMultipartFile {
	return s.Image
}

// SetImage sets the value of Image.
func (s *HumanDrawingPostReq) SetImage(val OptMultipartFile) {
	s.Image = val
}

// NewOptMultipartFile returns new OptMultipartFile with value set to v.
func NewOptMultipartFile(v ht.MultipartFile) OptMultipartFile {
	return OptMultipartFile{
		Value: v,
		Set:   true,
	}
}

// OptMultipartFile is optional ht.MultipartFile.
type OptMultipartFile struct {
	Value ht.MultipartFile
	Set   bool
}

// IsSet returns true if OptMultipartFile was set.
func (o OptMultipartFile) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMultipartFile) Reset() {
	var v ht.MultipartFile
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMultipartFile) SetTo(v ht.MultipartFile) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMultipartFile) Get() (v ht.MultipartFile, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMultipartFile) Or(d ht.MultipartFile) ht.MultipartFile {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SavedURLPostBadRequest struct {
	Error OptString `json:"error"`
}

// GetError returns the value of Error.
func (s *SavedURLPostBadRequest) GetError() OptString {
	return s.Error
}

// SetError sets the value of Error.
func (s *SavedURLPostBadRequest) SetError(val OptString) {
	s.Error = val
}

func (*SavedURLPostBadRequest) savedURLPostRes() {}

type SavedURLPostOK struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *SavedURLPostOK) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *SavedURLPostOK) SetMessage(val OptString) {
	s.Message = val
}

func (*SavedURLPostOK) savedURLPostRes() {}

type SavedURLPostReq struct {
	// The image file to upload.
	Image OptString `json:"image"`
}

// GetImage returns the value of Image.
func (s *SavedURLPostReq) GetImage() OptString {
	return s.Image
}

// SetImage sets the value of Image.
func (s *SavedURLPostReq) SetImage(val OptString) {
	s.Image = val
}

type UploadURLGetBadRequest struct {
	Error OptString `json:"error"`
}

// GetError returns the value of Error.
func (s *UploadURLGetBadRequest) GetError() OptString {
	return s.Error
}

// SetError sets the value of Error.
func (s *UploadURLGetBadRequest) SetError(val OptString) {
	s.Error = val
}

func (*UploadURLGetBadRequest) uploadURLGetRes() {}

type UploadURLGetOK struct {
	PresignedURL OptString `json:"presigned_url"`
}

// GetPresignedURL returns the value of PresignedURL.
func (s *UploadURLGetOK) GetPresignedURL() OptString {
	return s.PresignedURL
}

// SetPresignedURL sets the value of PresignedURL.
func (s *UploadURLGetOK) SetPresignedURL(val OptString) {
	s.PresignedURL = val
}

func (*UploadURLGetOK) uploadURLGetRes() {}
